#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Dec 10 18:46:43 -03 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto afbc0458fe324f9c918ab6faf9e9b526 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_hw_top_edu_bbt_behav xil_defaultlib.tb_hw_top_edu_bbt xil_defaultlib.glbl -log elaborate.log"
xelab -wto afbc0458fe324f9c918ab6faf9e9b526 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_hw_top_edu_bbt_behav xil_defaultlib.tb_hw_top_edu_bbt xil_defaultlib.glbl -log elaborate.log

