# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace2/TP_FINAL_Micro_ver7/TP_FINAL_Micro_ver7.srcs/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xci
# IP: The module: 'system_axi_gpio_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace2/TP_FINAL_Micro_ver7/TP_FINAL_Micro_ver7.gen/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace2/TP_FINAL_Micro_ver7/TP_FINAL_Micro_ver7.gen/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace2/TP_FINAL_Micro_ver7/TP_FINAL_Micro_ver7.gen/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace2/TP_FINAL_Micro_ver7/TP_FINAL_Micro_ver7.srcs/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xci
# IP: The module: 'system_axi_gpio_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace2/TP_FINAL_Micro_ver7/TP_FINAL_Micro_ver7.gen/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace2/TP_FINAL_Micro_ver7/TP_FINAL_Micro_ver7.gen/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace2/TP_FINAL_Micro_ver7/TP_FINAL_Micro_ver7.gen/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
