#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 10 18:46:51 -03 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_hw_top_edu_bbt_behav -key {Behavioral:sim_1:Functional:tb_hw_top_edu_bbt} -tclbatch tb_hw_top_edu_bbt.tcl -view /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace/MSE-SDC_ejercicio11/tb_hw_top_edu_bbt_behav.wcfg -log simulate.log"
xsim tb_hw_top_edu_bbt_behav -key {Behavioral:sim_1:Functional:tb_hw_top_edu_bbt} -tclbatch tb_hw_top_edu_bbt.tcl -view /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace/MSE-SDC_ejercicio11/tb_hw_top_edu_bbt_behav.wcfg -log simulate.log

