# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/pablo/Documentos/02_Maestria_en_Sistemas_Embebidos/21_Sistemas_Digitales_para_las_Comunicaciones/workspace/arty_A7-35_ejercicio11.xdc

# IP: ip/vio_0_3/vio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet
